---
- name: Copy Redis configuration file
  ansible.builtin.template:
    src: redis.conf.j2
    dest: "{{ redis_config_file }}"
    owner: "{{ redis_system_user }}"
    group: "{{ redis_system_group }}"
    mode: "0644"
  register: config_template
  no_log: true

- name: Copy Redis systemd unit file
  ansible.builtin.template:
    src: redis.service.j2
    dest: /etc/systemd/system/redis.service
    owner: root
    group: root
    mode: "0644"
  register: service_template
  no_log: true

- name: Daemon-reload Redis service
  become: true
  notify: Restart Redis service
  ansible.builtin.systemd:
    daemon_reload: true
    name: redis
  when: config_template is changed or service_template is changed # noqa: no-handler
  changed_when: config_template is changed or service_template is changed

- name: Ensure Redis service is enabled on boot
  become: true
  ansible.builtin.systemd:
    name: redis
    enabled: true
