---
- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Check if Redis is installed
  ansible.builtin.stat:
    path: /usr/local/bin/redis-server
  changed_when: false
  check_mode: false
  register: redis_is_installed

- name: Check current Redis version
  ansible.builtin.command: /usr/local/bin/redis-server --version
  changed_when: false
  failed_when: false
  check_mode: false
  register: redis_current_version
  when: redis_is_installed.stat.exists | bool

- name: "Enable overcommit memory"
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: 1
    sysctl_file: /etc/sysctl.d/redis.conf
    reload: true
    sysctl_set: true
