---
- name: Converge
  hosts: all
  #become: true

  # pre_tasks:
  #   - name: Update apt cache.
  #     apt: update_cache=true cache_valid_time=600
  #     when: ansible_os_family == 'Debian'

  #   - name: Clear out repo for Fedora.
  #     set_fact:
  #       redis_enablerepo: ""
  #     when: ansible_distribution == 'Fedora'

  # vars:
  #   redis_download_url: "https://ghfast.top/{{ redis_repo_url }}/releases/download/v{{ redis_roles_version }}/redis-{{ redis_version }}-{{ ansible_distribution }}-{{ ansible_distribution_version }}-{{ ansible_architecture }}.tar.gz"

  roles:
    - role: bernylinville.redis
