---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-errors: true
driver:
  name: docker
platforms:
  - name: instance
    image: "bernylinville/docker-${MOLECULE_DISTRO:-openeuler2403}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    hosts:
      all:
        vars:
          # 确保以 root 连接，避免触发 sudo
          ansible_user: root
          ansible_become: false
          # 明确 Python 解释器路径，避免探测错误
          ansible_python_interpreter: /usr/bin/python3
